name: LinkedIn Job Alert Bot

on:
  schedule:
    - cron: "0 */8 * * *"  # Every 8 hours
  workflow_dispatch:  # Optional: Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job alert script
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python linkedin_job_alert.py
